EXISTED_USER_REGISTRATION = 'User already exists'
NOT_ENOUGH_INFO_REGISTRATION = 'Email, password and name are required fields'
INCORRECT_INFO_LOGIN = 'email or password are incorrect'
NOT_AUTHORIZED = 'You should be authorised'
NO_INGREDIENTS = 'Ingredient ids must be provided'
INCORRECT_INGREDIENT = 'One or more ids provided are incorrect'
